export enum QueueStage {
  GATE_ENTRY = 'GATE_ENTRY',
  WAITING = 'WAITING',
  QUALITY_ASSAYING = 'QUALITY_ASSAYING',
  WEIGHING = 'WEIGHING',
  PROCUREMENT = 'PROCUREMENT',
  COMPLETED = 'COMPLETED'
}

export enum BookingStatus {
  DRAFT = 'DRAFT',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  ARRIVED = 'ARRIVED',
  IN_QUEUE = 'IN_QUEUE',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
  NO_SHOW = 'NO_SHOW'
}

export enum QualityResult {
  PASS = 'PASS',
  CONDITIONAL = 'CONDITIONAL',
  REJECTED = 'REJECTED'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  TRANSFERRED = 'TRANSFERRED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum UserRole {
  FARMER = 'FARMER',
  OPERATOR = 'OPERATOR',
  CENTRE_MANAGER = 'CENTRE_MANAGER',
  ADMIN = 'ADMIN'
}

export enum CentreStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PAUSED = 'PAUSED'
}
